language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_fd2b5160c5c3_key -iv $encrypted_fd2b5160c5c3_iv
  -in id_rsa.enc -out id_rsa -d
- echo $encrypted_fd2b5160c5c3_key
- echo $encrypted_fd2b5160c5c3_iv
- git config --global user.name "fate0"
- git config --global user.email "fate0@fatezero.org"
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo g
- hexo d
branches:
  only:
  - markdown
